### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by ghost1372** [mirkoBastianini/AndroRAT#2]
hi
i cant compile client
some library dosnt exist

**Comment by mirkoBastianini** [comment]
You must follow my guide to import libraries in eclipse. It's working 100%.

2016-05-12 7:50 GMT-01:00 ghost1372 <notifications@github.com>:

**Comment by ghost1372** [comment]
i follow your guide but i mean client! not server!
i cant compile apk because there is alot of error in imports and classes

**Comment by mirkoBastianini** [comment]
Which errors?

2016-05-12 8:45 GMT-01:00 ghost1372 <notifications@github.com>:

**Comment by ghost1372** [comment]
![5](https://cloud.githubusercontent.com/assets/9213496/15210770/19f747dc-184d-11e6-8d72-3c9c5b380398.png)
![6](https://cloud.githubusercontent.com/assets/9213496/15210771/1a036116-184d-11e6-8a7e-d03901aea801.png)
![1](https://cloud.githubusercontent.com/assets/9213496/15210772/1a0a69b6-184d-11e6-9a0c-d0b2972190cc.png)
![2](https://cloud.githubusercontent.com/assets/9213496/15210773/1a1115ea-184d-11e6-93c4-721701cd095f.png)
![3](https://cloud.githubusercontent.com/assets/9213496/15210774/1a1940f8-184d-11e6-9c77-dc55826b9c47.png)
![4](https://cloud.githubusercontent.com/assets/9213496/15210775/1a219c58-184d-11e6-825f-0dad4753bb28.png)

**Comment by mirkoBastianini** [comment]
Go on and import the server.... the libraries are shared between server and
client

2016-05-12 8:54 GMT-01:00 ghost1372 <notifications@github.com>:

**Comment by ghost1372** [comment]
i follow guides to import server but server dosnt exist!
i think some files is missing.
can you give me full source code from mirror link?
![1](https://cloud.githubusercontent.com/assets/9213496/15211761/63726252-1852-11e6-8223-d54bee7c9b86.png)

**Comment by mirkoBastianini** [comment]
You must import the client in Eclipse, not in Android Studio....

2016-05-12 9:31 GMT-01:00 ghost1372 <notifications@github.com>:

**Comment by ghost1372** [comment]
i do it in eclipse.
i have problem too

**Comment by a-nightcrawler** [comment]
hi, the problem is you are missing every class inside InOut directory, to fix it you just copy this entire directory and paste it in AndroRAT/app/src/main/java. let me know if that works.

**Comment by ghost1372** [comment]
not work

**Comment by a-nightcrawler** [comment]
can you show any screenshot of your project package tree structure, just to be sure you put the classes in the right path.

**Comment by chiccofx** [comment]
No matter what I do, I cannot import the AndroRATServer directory as a project. It seems it is missing the relevant project settings files from the original project. The documentation is very shallow and does not describe the full setup process. Can you please indicate the instructions for compiling both the APK and the Server?

**Comment by chiccofx** [comment]
Just so you know, all that is needed in order for it to work is to import the .project and .classpath from the original project, that are missing and/or wrongly configured on this project.
