### ISSUE TITLE
video streaming

### ISSUE THREAD

**Issue by alegd** [mirkoBastianini/AndroRAT#3]
in functionalities list appear video streaming but it seems that just does not work properly. any advice?

**Comment by mirkoBastianini** [comment]
For now i can't implement it, because i haven't spare time (aarghhh work
and university...)

2016-05-12 21:54 GMT+02:00 a-nightcrawler <notifications@github.com>:

**Comment by a-nightcrawler** [comment]
ok, thanks for reply, now I know that this feature is not implemented and I am not the problem. you by any chance have any ideas, references or documentation you can point to me? I would like to make this work and read all necessary RFCs consume a lot of time and funny thing is that like you I got university and work... by the way your version of androrat rocks, great job.

**Comment by mirkoBastianini** [comment]
We can talk in private. Mirko.bastianini@gmail.com
Il 13/mag/2016 02:55, "a-nightcrawler" <notifications@github.com> ha
scritto:
